server:
  port: ${PORT:8080}

spring:
  application:
    name: Mercado Lance
  servlet:
    context-path: /mercado-lance

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_JWT_ISSUER}

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
      exposure:
        include: health

front:
  url: ${FRONT_URL}